apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: {{ $.Release.Namespace }}
  labels:
    app: mysql-headless
spec:
  clusterIP: None
  selector:
    name: mysql
  ports:
    - name: mysql
      port: 8001