kind: ConfigMap
apiVersion: v1
metadata:
  name: my.cnf
  namespace: {{ $.Release.Namespace }}
data:
  my.cnf: |-
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_general_ci
    skip-character-set-client-handshake=1
    [client]
    default-character-set=utf8
    [mysql]
    default-character-set=utf8
    
