---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: {{ $.Release.Namespace }}
  labels:
    name: redis
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    name: redis
  type: ClusterIP
