{{- range $tmpindex, $rbtmq := until ( int $.Values.mq.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: rabbitmq{{ $index }}
spec:
  ports:
    - name: aigniq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: pz25fe
      protocol: TCP
      port: 15672
      targetPort: 15672
  selector:
    name: rabbitmq{{ $index }}
  type: ClusterIP
---

{{- end }}


  # sessionAffinity: None
  # ipFamilies:
  #   - IPv4
  # ipFamilyPolicy: SingleStack
  # internalTrafficPolicy: Cluster