{{- range $tmpindex, $rbtmq := until ( int $.Values.mq.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: rabbitmq{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq{{ $index }}
  template:
    metadata:
      labels:
        name: rabbitmq{{ $index }}
    spec:
      containers:
        - name: rabbitmq{{ $index }}
          image: {{ $.Values.mq.image }}
          ports:
            - name: mq
              containerPort: 5672
              protocol: TCP
            - name: web
              containerPort: 15672
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
{{- end }}

