{{- range $tmpindex, $gateway := until ( int $.Values.gateway.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: gateway{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway{{ $index }}
  template:
    metadata:
      labels:
        name: gateway{{ $index }}
    spec:
      containers:
        - name: gateway{{ $index }}
          image: {{ $.Values.gateway.image }}
          env:
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
          command:
            - java
          args:
            - '-jar'
            - '-Dfile.encoding=UTF-8'
            - /applications/gateway.jar
            - '--spring.profiles.active=demo{{ $index }}'
            
            - '--server.port=8080'
            - '--spring.datasource.druid.username=primihub'
            - '--spring.datasource.druid.password=primihub@123'
            - >-
              --spring.datasource.druid.url=jdbc:mysql://mysql.{{ $.Release.Namespace }}:3306/fusion?characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
            - '--spring.cloud.nacos.discovery.server-addr=nacos:8848'
            - '--nacos.config.server-addr=nacos:8848'
            {{ if eq $index 1 }}
            - '--spring.cloud.nacos.discovery.namespace=46b6b568-e6ae-45ca-baa1-819932fc8947'
            - '--nacos.config.namespace=46b6b568-e6ae-45ca-baa1-819932fc8947'
            {{ else if eq $index 2 }}
            - '--spring.cloud.nacos.discovery.namespace=71843998-b60a-42ed-81d7-c3c9940d11c0'
            - '--nacos.config.namespace=71843998-b60a-42ed-81d7-c3c9940d11c0'
            {{ else if eq $index 3 }}
            - '--spring.cloud.nacos.discovery.namespace=35674f9d-3369-42f6-9f30-c8de2535adc6'
            - '--nacos.config.namespace=35674f9d-3369-42f6-9f30-c8de2535adc6'
            {{ end }}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 10
---
{{- end }}
