{{- range $tmpindex, $app := until ( int $.Values.application.num )}} 
{{- $index := add $tmpindex 1 -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-volume-{{ $index }}
  labels:
    name: application{{ $index }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
{{- end }}
