
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: $NAMESPACE
  labels:
    name: redis
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      volumes:
        - name: volume-inx7a
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
            defaultMode: 420
      containers:
        - name: redis
          image: 'redis:5'
          command:
            - redis-server
          args:
            - /usr/local/etc/redis/redis.conf
          resources: {}
          volumeMounts:
            - name: volume-inx7a
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: $NAMESPACE
  labels:
    name: redis
spec:
  ports:
    - name: qxgwm2
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    name: redis
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: $NAMESPACE
data:
  redis.conf: |-
    daemonize no
    pidfile /data/redis.pid
    port 6379
    bind 0.0.0.0
    timeout 0
    requirepass primihub
    dbfilename dump.rdb
    dir /data