
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fusion
  namespace: $NAMESPACE
  labels:
    name: fusion
  annotations:
    workload: fusion
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fusion
  template:
    metadata:
      labels:
        name: fusion
    spec:
      containers:
        - name: fusion
          image: '$FUSION_IMAGE'
          command:
            - java
          args:
            - '-jar'
            - '-Dfile.encoding=UTF-8'
            - /applications/fusion.jar
            - '--spring.profiles.active=demo'
            - '--server.port=8080'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 10

---
kind: Service
apiVersion: v1
metadata:
  name: fusion
  namespace: $NAMESPACE
  labels:
    name: fusion
  annotations:
    workload: fusion
spec:
  ports:
    - name: fusion
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30803
  selector:
    name: fusion
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

